library(base64enc)
library(tidyverse)

load('log.Rdata')

# Retrieve the log from swirl's state

share_completed <- function(log){
    user <- log$user
    share_completed <- mean(as.logical(base64decode(log$encoded_skip)), na.rm = TRUE)
    return(c(user, share_completed))
}

graded <- share_completed(log)

print(paste('User', graded[1], 'completed', graded[2], 'of the questions.'))

#output_hash='InVzZXIiLCJjb3Vyc2VfbmFtZSIsImxlc3Nvbl9uYW1lIiwicXVlc3Rpb25fbnVtYmVyIiwiY29ycmVjdCIsImF0dGVtcHQiLCJza2lwcGVkIiwiZW5jb2RlZF9za2lwIiwiZGF0ZXRpbWUiDQoia3lsZSIsIkRhdGEgU2NpZW5jZSBmb3IgRWNvbm9taXN0cyIsIkdHUGxvdDIgRGVtbyIsNCxUUlVFLDEsVFJVRSwiQVFFQkFRRUJBUUVBIiwxNzI1NTM4NzkwLjIxODkyDQoia3lsZSIsIkRhdGEgU2NpZW5jZSBmb3IgRWNvbm9taXN0cyIsIkdHUGxvdDIgRGVtbyIsNSxUUlVFLDEsVFJVRSwiQVFFQkFRRUJBUUVBIiwxNzI1NTM4NzkxLjY0MzA2DQoia3lsZSIsIkRhdGEgU2NpZW5jZSBmb3IgRWNvbm9taXN0cyIsIkdHUGxvdDIgRGVtbyIsOCxUUlVFLDEsVFJVRSwiQVFFQkFRRUJBUUVBIiwxNzI1NTM4Nzk2LjY3MDY3DQoia3lsZSIsIkRhdGEgU2NpZW5jZSBmb3IgRWNvbm9taXN0cyIsIkdHUGxvdDIgRGVtbyIsOSxUUlVFLDEsVFJVRSwiQVFFQkFRRUJBUUVBIiwxNzI1NTM4ODA4Ljc3NDM4DQoia3lsZSIsIkRhdGEgU2NpZW5jZSBmb3IgRWNvbm9taXN0cyIsIkdHUGxvdDIgRGVtbyIsMTAsVFJVRSwxLFRSVUUsIkFRRUJBUUVCQVFFQSIsMTcyNTUzODgxMi43MjM0Mg0KImt5bGUiLCJEYXRhIFNjaWVuY2UgZm9yIEVjb25vbWlzdHMiLCJHR1Bsb3QyIERlbW8iLDEzLFRSVUUsMSxUUlVFLCJBUUVCQVFFQkFRRUEiLDE3MjU1Mzg4MTYuMTcxMTQNCiJreWxlIiwiRGF0YSBTY2llbmNlIGZvciBFY29ub21pc3RzIiwiR0dQbG90MiBEZW1vIiwxNCxUUlVFLDEsVFJVRSwiQVFFQkFRRUJBUUVBIiwxNzI1NTM4ODE4LjU2MzUyDQoia3lsZSIsIkRhdGEgU2NpZW5jZSBmb3IgRWNvbm9taXN0cyIsIkdHUGxvdDIgRGVtbyIsMTYsVFJVRSwxLFRSVUUsIkFRRUJBUUVCQVFFQSIsMTcyNTUzODgyMi4xMTc4MQ0KImt5bGUiLCJEYXRhIFNjaWVuY2UgZm9yIEVjb25vbWlzdHMiLCJHR1Bsb3QyIERlbW8iLDE4LE5BLDEsRkFMU0UsIkFRRUJBUUVCQVFFQSIsMTcyNTUzODgyNS44MzgxOQ0K'

swirlify::google_form_decode('swirl.csv')

read_csv(rawToChar(base64decode(as.character(output_hash))))